/**
 * The title overlay used on every social image — Pinterest pins and Instagram
 * posts alike. One implementation so the type looks identical wherever a post
 * shows up, and a pin design change lands on Instagram for free.
 *
 * Text is composited as SVG rather than generated by the image model, so it
 * stays crisp and consistent.
 *
 * Style: "Tabloid Bold" — Inter Black, all-caps, a yellow eyebrow badge, an
 * optional single highlighted word/phrase, and a warm red-black scrim. Picked
 * 2026-07-28 to match the blog's move to clickbait-worded titles; see
 * STYLE.md's "Titles" section. If the look changes again, this is the one
 * place to edit — Instagram stories inherit it automatically.
 */
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { Resvg } from '@resvg/resvg-js';

// Brand tokens, kept in sync with public/assets/style.css
export const GREEN_900 = '#123a26';
export const GREEN_500 = '#34c77b';

// Tabloid Bold palette
export const SCRIM_DARK = '#2a0d02';
export const SCRIM_MID = '#3a1204';
export const BADGE_YELLOW = '#ffb703';

const HERE = dirname(fileURLToPath(import.meta.url));
const FONTS = [join(HERE, '../fonts/Fraunces.ttf'), join(HERE, '../fonts/Inter.ttf')];

const esc = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Title tracking. Anything measured for the title must be measured with this. */
const TITLE_TRACKING = -0.5;

// Eyebrow badge type. The badge sets looser than the title, so it has to be
// measured with its own tracking.
const BADGE_FONT = 24;
const BADGE_TRACKING = 0.5;
const BADGE_PAD_X = 18;

/**
 * Ink box of one run of text as Inter Black will actually set it.
 *
 * Returns `{ x, width }` in the coordinate space of a `<text>` drawn at x=0.
 * `x` is the left side bearing: the gap between the text anchor and the first
 * glyph's ink. It matters for the badge, where the rectangle has to sit an
 * equal distance from the ink on both sides, not from the anchor.
 *
 * `tracking` must match the letter-spacing the caller actually renders with.
 * Measuring at one tracking and drawing at another is a per-character error,
 * which on a 14-character badge label is most of a side's padding.
 */
const boxCache = new Map();
function measureBox(text, fontSize, tracking = TITLE_TRACKING) {
  const key = `${fontSize} ${tracking} ${text}`;
  const hit = boxCache.get(key);
  if (hit !== undefined) return hit;

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="10000" height="${fontSize * 3}"><text font-family="Inter" font-size="${fontSize}" font-weight="900" letter-spacing="${tracking}" x="0" y="${fontSize * 1.5}">${esc(text)}</text></svg>`;
  const bbox = new Resvg(svg, {
    font: { fontFiles: FONTS, loadSystemFonts: false, defaultFontFamily: 'Inter' },
  }).getBBox();

  // An empty or whitespace-only line has no bbox at all.
  const box = { x: bbox?.x ?? 0, width: bbox?.width ?? 0 };
  boxCache.set(key, box);
  return box;
}

/** Width of one line as Inter Black will actually set it. */
function measure(text, fontSize, tracking = TITLE_TRACKING) {
  return measureBox(text, fontSize, tracking).width;
}

/** Greedy word wrap against measured widths. */
function wrap(text, fontSize, maxWidth) {
  const lines = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    const candidate = line ? `${line} ${word}` : word;
    if (measure(candidate, fontSize) > maxWidth && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/** Shrink the title until it fits in at most maxLines. */
function fitTitle(title, maxWidth, maxLines) {
  for (const size of [70, 64, 58, 52, 46, 40]) {
    const lines = wrap(title, size, maxWidth);
    if (lines.length <= maxLines) return { size, lines };
  }
  const size = 40;
  return { size, lines: wrap(title, size, maxWidth).slice(0, maxLines) };
}

/**
 * Split a wrapped line into [before, highlighted, after] against an
 * upper-cased highlight phrase. Returns the whole line as `before` (no
 * highlight) if the phrase doesn't sit wholly inside this line — safer than
 * a partial match that would color half a word.
 */
function splitHighlight(line, highlight) {
  if (!highlight) return [line, '', ''];
  const i = line.indexOf(highlight);
  if (i === -1) return [line, '', ''];
  return [line.slice(0, i), line.slice(i, i + highlight.length), line.slice(i + highlight.length)];
}

/**
 * Build the SVG overlay for one image.
 *
 * @param {object} opts
 * @param {number} opts.width    canvas width in px
 * @param {number} opts.height   canvas height in px
 * @param {string} opts.title    headline to set (rendered upper-case)
 * @param {string} [opts.eyebrow]   short badge label above the title, e.g.
 *   "WATERING MISTAKE" (2-4 words). Omit to skip the badge.
 * @param {string} [opts.highlight] a word or short phrase from the title to
 *   render in the yellow accent color. Must appear verbatim (case-insensitive)
 *   inside the title, and must land wholly within one wrapped line or it's
 *   ignored — a broken highlight is worse than none.
 * @param {number} [opts.pad]    edge padding
 * @param {number} [opts.maxLines]
 * @param {number} [opts.bottomOffset]  lift the text block off the bottom edge.
 *   Stories use this to keep the last third clear for a link sticker.
 * @param {number} [opts.scrimStart]  where the fade begins, as a fraction of
 *   height. The 0.32 default is the pin design; don't change it without
 *   re-running rebuild-images.mjs, or pins will drift out of sync with it.
 */
export function buildOverlay({
  width,
  height,
  title,
  eyebrow,
  highlight,
  pad = 72,
  maxLines = 5,
  bottomOffset = 0,
  scrimStart = 0.32,
}) {
  const upperTitle = title.toUpperCase();
  const upperHighlight = highlight ? highlight.toUpperCase() : undefined;
  const maxWidth = width - pad * 2;
  const { size, lines } = fitTitle(upperTitle, maxWidth, maxLines);
  const lineHeight = Math.round(size * 1.14);
  const blockH = lines.length * lineHeight;

  const badgeH = 52;
  const badgeGap = eyebrow ? 26 : 0;
  const titleBottom = height - pad - bottomOffset;
  const titleTop = titleBottom - blockH;
  const badgeTop = titleTop - badgeGap - badgeH;

  // The fade is anchored to the canvas, not the text block, so a taller title
  // never drags the gradient up the frame and swallows the photo.
  const scrimTop = height * scrimStart;

  const tspans = lines
    .map((l, i) => {
      const y = titleTop + i * lineHeight + size * 0.8;
      const [before, hi, after] = splitHighlight(l, upperHighlight);
      if (!hi) return `<tspan x="${pad}" y="${y}">${esc(l)}</tspan>`;
      return `<tspan x="${pad}" y="${y}">${esc(before)}<tspan fill="${BADGE_YELLOW}">${esc(hi)}</tspan>${esc(after)}</tspan>`;
    })
    .join('');

  // Measure the badge exactly as it is drawn: upper-cased, at 24px, with the
  // badge's own positive tracking. Then pull the anchor left by the side
  // bearing so the ink starts BADGE_PAD_X from the rectangle's edge and the
  // rectangle ends BADGE_PAD_X past it. Equal gaps on both sides.
  const eyebrowText = eyebrow ? eyebrow.toUpperCase() : '';
  const eyebrowBox = eyebrow ? measureBox(eyebrowText, BADGE_FONT, BADGE_TRACKING) : null;
  const eyebrowWidth = eyebrowBox ? Math.round(eyebrowBox.width) + BADGE_PAD_X * 2 : 0;
  const badge = eyebrow
    ? `<rect x="${pad}" y="${badgeTop}" width="${eyebrowWidth}" height="${badgeH}" rx="8" fill="${BADGE_YELLOW}"/>
  <text x="${pad + BADGE_PAD_X - eyebrowBox.x}" y="${badgeTop + 34}" font-family="Inter" font-size="${BADGE_FONT}" font-weight="900" letter-spacing="${BADGE_TRACKING}" fill="${SCRIM_DARK}">${esc(eyebrowText)}</text>`
    : '';

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <defs>
    <linearGradient id="scrim" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="#1a0a02" stop-opacity="0"/>
      <stop offset="38%"  stop-color="${SCRIM_MID}" stop-opacity="0.55"/>
      <stop offset="70%"  stop-color="${SCRIM_MID}" stop-opacity="0.9"/>
      <stop offset="100%" stop-color="${SCRIM_DARK}" stop-opacity="0.97"/>
    </linearGradient>
  </defs>

  <rect x="0" y="${scrimTop}" width="${width}" height="${height - scrimTop}" fill="url(#scrim)"/>

  ${badge}

  <!-- title -->
  <text font-family="Inter" font-size="${size}" font-weight="900" letter-spacing="-0.5" fill="#ffffff">${tspans}</text>
</svg>`;
}
