#!/usr/bin/env node
/**
 * Turn one generated master photo into the two images a blog post needs:
 *
 *   <slug>-hero.jpg  1200x800  clean photo, no text. Used as the on-page hero
 *                              and as og:image / twitter:image for link shares.
 *   <slug>-pin.jpg   1000x1500 same photo, 2:3 portrait, with the post title
 *                              overlaid in brand type. This is what the Pin
 *                              button hands to Pinterest.
 *
 * Text is composited here rather than generated by the image model, so the
 * type is crisp and identical on every pin.
 *
 * Usage:
 *   node scripts/make-images.mjs <master.png> <slug> "<title for the pin>" [heroCrop]
 *
 * heroCrop controls which band of the tall master becomes the wide hero:
 *   attention (default) — sharp picks the busiest region. Right for a single
 *                         clear subject (a caterpillar, an egg cluster).
 *   centre / south / north — fixed bands. Use when the story is in a specific
 *                         part of the frame and "busiest" picks the wrong one,
 *                         e.g. a tall tree over a dying bed, where the point is
 *                         at the bottom (south) and the canopy is just texture.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import sharp from 'sharp';
import { Resvg } from '@resvg/resvg-js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const OUT = join(ROOT, 'public/assets/blog');
const FONTS = [join(HERE, 'fonts/Fraunces.ttf'), join(HERE, 'fonts/Inter.ttf')];

// Brand tokens, kept in sync with public/assets/style.css
const GREEN_900 = '#123a26';
const GREEN_500 = '#34c77b';

const PIN_W = 1000;
const PIN_H = 1500;
const PAD = 72;

const esc = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * Greedy word wrap. Fraunces at 600 weight averages ~0.50em per character,
 * which is close enough to keep lines inside maxWidth with the padding we use.
 */
function wrap(text, fontSize, maxWidth) {
  const perChar = fontSize * 0.5;
  const maxChars = Math.floor(maxWidth / perChar);
  const lines = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    const candidate = line ? `${line} ${word}` : word;
    if (candidate.length > maxChars && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/** Shrink the title until it fits in at most 5 lines. */
function fitTitle(title, maxWidth) {
  for (const size of [78, 72, 66, 60, 54, 48]) {
    const lines = wrap(title, size, maxWidth);
    if (lines.length <= 5) return { size, lines };
  }
  const size = 48;
  return { size, lines: wrap(title, size, maxWidth).slice(0, 5) };
}

function buildOverlay(title) {
  const maxWidth = PIN_W - PAD * 2;
  const { size, lines } = fitTitle(title, maxWidth);
  const lineHeight = Math.round(size * 1.16);
  const blockH = lines.length * lineHeight;

  // Title block sits in the lower third, above the brand footer.
  const footerY = PIN_H - PAD - 20;
  const titleBottom = footerY - 74;
  const titleTop = titleBottom - blockH;

  const tspans = lines
    .map(
      (l, i) =>
        `<tspan x="${PAD}" y="${titleTop + i * lineHeight + size * 0.8}">${esc(l)}</tspan>`
    )
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${PIN_W}" height="${PIN_H}" viewBox="0 0 ${PIN_W} ${PIN_H}">
  <defs>
    <linearGradient id="scrim" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="${GREEN_900}" stop-opacity="0"/>
      <stop offset="38%"  stop-color="${GREEN_900}" stop-opacity="0.42"/>
      <stop offset="62%"  stop-color="${GREEN_900}" stop-opacity="0.82"/>
      <stop offset="100%" stop-color="${GREEN_900}" stop-opacity="0.96"/>
    </linearGradient>
    <linearGradient id="topfade" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="${GREEN_900}" stop-opacity="0.50"/>
      <stop offset="100%" stop-color="${GREEN_900}" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="mark" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#7fbf8f"/>
      <stop offset="100%" stop-color="#3aa6b8"/>
    </linearGradient>
  </defs>

  <rect x="0" y="0" width="${PIN_W}" height="220" fill="url(#topfade)"/>
  <rect x="0" y="${PIN_H * 0.34}" width="${PIN_W}" height="${PIN_H * 0.66}" fill="url(#scrim)"/>

  <!-- eyebrow -->
  <text x="${PAD}" y="${PAD + 34}" font-family="Inter" font-size="23" font-weight="700"
        fill="#ffffff" opacity="0.92" letter-spacing="3.4">GARDEN PRO PLANNER</text>

  <!-- accent rule -->
  <rect x="${PAD}" y="${titleTop - 40}" width="86" height="6" rx="3" fill="${GREEN_500}"/>

  <!-- title -->
  <text font-family="Fraunces" font-size="${size}" font-weight="700" fill="#ffffff">${tspans}</text>

  <!-- brand footer -->
  <rect x="${PAD}" y="${footerY - 34}" width="44" height="44" rx="12" fill="url(#mark)"/>
  <text x="${PAD + 22}" y="${footerY - 2}" font-family="Fraunces" font-size="27" font-weight="700"
        fill="#ffffff" text-anchor="middle">G</text>
  <text x="${PAD + 60}" y="${footerY - 3}" font-family="Inter" font-size="25" font-weight="600"
        fill="#ffffff" opacity="0.95">thegardenplanner.app</text>
</svg>`;
}

const CROPS = {
  attention: sharp.strategy.attention,
  entropy: sharp.strategy.entropy,
  centre: 'centre',
  center: 'centre',
  north: 'north',
  south: 'south',
};

async function main() {
  const [master, slug, title, heroCrop = 'attention'] = process.argv.slice(2);
  if (!master || !slug || !title) {
    console.error('usage: node scripts/make-images.mjs <master.png> <slug> "<title>" [heroCrop]');
    process.exit(1);
  }
  const position = CROPS[heroCrop];
  if (position === undefined) {
    console.error(`unknown crop "${heroCrop}" (use: ${Object.keys(CROPS).join(', ')})`);
    process.exit(1);
  }
  mkdirSync(OUT, { recursive: true });
  const src = readFileSync(master);

  // Hero: clean wide crop, no text.
  await sharp(src)
    .resize(1200, 800, { fit: 'cover', position })
    .jpeg({ quality: 80, mozjpeg: true })
    .toFile(join(OUT, `${slug}-hero.jpg`));

  // Pin: full-bleed 2:3 with the title overlaid.
  const base = await sharp(src)
    .resize(PIN_W, PIN_H, { fit: 'cover', position: sharp.strategy.attention })
    .toBuffer();

  const svg = buildOverlay(title);
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: PIN_W },
    font: { fontFiles: FONTS, loadSystemFonts: false, defaultFontFamily: 'Inter' },
  });
  const overlay = resvg.render().asPng();

  await sharp(base)
    .composite([{ input: overlay, top: 0, left: 0 }])
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(join(OUT, `${slug}-pin.jpg`));

  console.log(`${slug}: hero + pin written to public/assets/blog/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
