#!/usr/bin/env node
/**
 * Turn one generated master photo into the two images a blog post needs:
 *
 *   <slug>-hero.jpg  1200x800  clean photo, no text. Used as the on-page hero
 *                              and as og:image / twitter:image for link shares.
 *   <slug>-pin.jpg   1000x1500 same photo, 2:3 portrait, with the post title
 *                              overlaid in brand type. This is what the Pin
 *                              button hands to Pinterest.
 *
 * Text is composited here rather than generated by the image model, so the
 * type is crisp and identical on every pin.
 *
 * Usage:
 *   node scripts/make-images.mjs <master.png> <slug> "<title for the pin>" [heroCrop] [--eyebrow "TEXT"] [--highlight "WORD OR PHRASE"]
 *
 * --eyebrow is a short (2-4 word) badge label shown above the title, e.g.
 *   "WATERING MISTAKE". Omit for no badge.
 * --highlight is a word or phrase from the title to render in the accent
 *   color. Must match the title verbatim (case-insensitive) or it's ignored.
 *
 * heroCrop controls which band of the tall master becomes the wide hero:
 *   attention (default) — sharp picks the busiest region. Right for a single
 *                         clear subject (a caterpillar, an egg cluster).
 *   centre / south / north — fixed bands. Use when the story is in a specific
 *                         part of the frame and "busiest" picks the wrong one,
 *                         e.g. a tall tree over a dying bed, where the point is
 *                         at the bottom (south) and the canopy is just texture.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import sharp from 'sharp';
import { Resvg } from '@resvg/resvg-js';
import { buildOverlay } from './lib/overlay.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const OUT = join(ROOT, 'public/assets/blog');
const FONTS = [join(HERE, 'fonts/Fraunces.ttf'), join(HERE, 'fonts/Inter.ttf')];

const PIN_W = 1000;
const PIN_H = 1500;

const CROPS = {
  attention: sharp.strategy.attention,
  entropy: sharp.strategy.entropy,
  centre: 'centre',
  center: 'centre',
  north: 'north',
  south: 'south',
};

function flag(args, name) {
  const i = args.indexOf(`--${name}`);
  return i > -1 ? args[i + 1] : undefined;
}

async function main() {
  const args = process.argv.slice(2);
  const eyebrow = flag(args, 'eyebrow');
  const highlight = flag(args, 'highlight');
  const positional = args.filter((a, i) => {
    if (a.startsWith('--')) return false;
    if (args[i - 1] === '--eyebrow' || args[i - 1] === '--highlight') return false;
    return true;
  });
  const [master, slug, title, heroCrop = 'attention'] = positional;
  if (!master || !slug || !title) {
    console.error('usage: node scripts/make-images.mjs <master.png> <slug> "<title>" [heroCrop] [--eyebrow "TEXT"] [--highlight "WORD"]');
    process.exit(1);
  }
  const position = CROPS[heroCrop];
  if (position === undefined) {
    console.error(`unknown crop "${heroCrop}" (use: ${Object.keys(CROPS).join(', ')})`);
    process.exit(1);
  }
  mkdirSync(OUT, { recursive: true });
  const src = readFileSync(master);

  // Hero: clean wide crop, no text.
  await sharp(src)
    .resize(1200, 800, { fit: 'cover', position })
    .jpeg({ quality: 80, mozjpeg: true })
    .toFile(join(OUT, `${slug}-hero.jpg`));

  // Pin: full-bleed 2:3 with the title overlaid.
  const base = await sharp(src)
    .resize(PIN_W, PIN_H, { fit: 'cover', position: sharp.strategy.attention })
    .toBuffer();

  const svg = buildOverlay({ width: PIN_W, height: PIN_H, title, eyebrow, highlight });
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: PIN_W },
    font: { fontFiles: FONTS, loadSystemFonts: false, defaultFontFamily: 'Inter' },
  });
  const overlay = resvg.render().asPng();

  await sharp(base)
    .composite([{ input: overlay, top: 0, left: 0 }])
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(join(OUT, `${slug}-pin.jpg`));

  console.log(`${slug}: hero + pin written to public/assets/blog/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
